name: Validate

on:
  pull_request:
    branches: [master, dev]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: nrwl/nx-set-shas@v3
        with:
          main-branch-name: 'dev'

      - name: Install dependencies
        run: npm clean-install

      - name: Build Front End
        run: npm run build:www:dev

      - name: Build Back End
        run: npm run build:api:dev

      - name: Prettier
        run: npm run lint:prettier

      - name: ESLint
        run: npm run lint:eslint

      - name: API Test
        run: npm run test:api

      - name: Client Test
        run: npm run test:www

      - name: End To End test (Cypress)
        uses: cypress-io/github-action@v4
        with:
          # Start the api, then start the web-client ( `3333` and `4200`)
          start: npm run serve:api, npm run serve:www
          # Since the backend is initialize first, we just need to wait until web-client be available
          wait-on: 'http://localhost:4200'
          working-directory: apps/client-website-e2e
          install: false
